### ISSUE TITLE
Potential logic issue in computing global_quiescent_epoch

### ISSUE THREAD

**Issue by cynecx** [komora-io/ebr#1]
https://github.com/komora-io/ebr/blob/9d380ef36510e9874ed7bf9e4bbaaf5f7aa174a6/src/lib.rs#L152

IIuc, this always reduces to zero which doesn't seem correct to me. Ideally `SharedLocalState` should provide a method similar to [`Iterator::reduce`](https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html#method.reduce), so it would turn into:

```rust
let global_quiescent_epoch = self
    .local_progress_registry
    .reduce(|min, this| min.min(this.load(Acquire)))
    .unwrap_or(0);
```

**Comment by spacejam** [comment]
Thanks for reporting this! This has been fixed
